### ISSUE TITLE
What about nested object/arrays?

### ISSUE THREAD

**Issue by Allez1433** [rasheedsaqib/firefose#1]
Hi,

I've been trying out this package in the last couple of days, but have a question regarding the nested objects within a schema.

Say I had the following structure:

```
profiles: { 
      profile1: {
        id: {
            type: String,
            default: '1'
        },
        firstName: {
            type: String,
            default: 'Mike'
        },
        avatar: {
            type: String,
            default: ''
        },
        isPending: {
            type: Boolean,
            default: true
        }
      },
      profile2: {
        id: {
            type: String,
            default: '2'
        },
        firstName: {
            type: String,
            default: 'Jack'
        },
        avatar: {
            type: String,
            default: ''
        },
        isPending: {
            type: Boolean,
            default: true
        }
      },
};
```
How can I make this work, as at the moment it doesn't seem to loop through the object and set the default values of the child fields?

**Comment by rasheedsaqib** [comment]
You are trying to do "Schema inside a Schema".  This is not supported at the moment. You can only use refrences to other schemas inside a schema. 
For this scenario you can use Object type:
`const profilesSchema = Schema({
    profile1: {
        type: Object,
        default: {
            id: '1',
            firstName: 'Mike',
            avatar: '',
            isPending: true
        }
    },
    profile2: {
        type: Object,
        default: {
            id: '2',
            firstName: 'Jack',
            avatar: '',
            isPending: true
        }
    }
})`

**Comment by rasheedsaqib** [comment]
You are trying to do "Schema inside a Schema". This is not supported at the moment. You can only use refrences to other schemas inside a schema.
For this scenario you can use Object type:
`
const profilesSchema = Schema({
    profile1: {
        type: Object,
        default: {
            id: '1',
            firstName: 'Mike',
            avatar: '',
            isPending: true
        }
    },
    profile2: {
        type: Object,
        default: {
            id: '2',
            firstName: 'Jack',
            avatar: '',
            isPending: true
        }
    }
})
`

**Comment by rasheedsaqib** [comment]
const profilesSchema = Schema({
    profile1: {
        type: Object,
        default: {
            id: '1',
            firstName: 'Mike',
            avatar: '',
            isPending: true
        }
    },
    profile2: {
        type: Object,
        default: {
            id: '2',
            firstName: 'Jack',
            avatar: '',
            isPending: true
        }
    }
})

**Comment by rasheedsaqib** [comment]
> const profilesSchema = Schema({
    profile1: {
        type: Object,
        default: {
            id: '1',
            firstName: 'Mike',
            avatar: '',
            isPending: true
        }
    },
    profile2: {
        type: Object,
        default: {
            id: '2',
            firstName: 'Jack',
            avatar: '',
            isPending: true
        }
    }
})

**Comment by rasheedsaqib** [comment]
You cann not specify a schema this way. You will have to use Object type.
```
const profilesSchema = Schema({
    profile1: {
        type: Object,
        default: {
            id: '1',
            firstName: 'Mike',
            avatar: '',
            isPending: true
        }
    },
    profile2: {
        type: Object,
        default: {
            id: '2',
            firstName: 'Jack',
            avatar: '',
            isPending: true
        }
    }
})
```

**Comment by BoBch27** [comment]
Got it. Thank you!

**Comment by Allez1433** [comment]
Got it, thank you!

**Comment by jespinozaa** [comment]
Hi, I've been trying this package too, and I can't define a schema for an attribute of type array with json objects: 

example:

`data [{ key: "obj1"},{key: "obj2"}]
`
I tried this but it didn't work, could you help me?
 
```
const SessionSchema = new Schema({

  username: {
    type: String,
  },
  dateSession: {
    type: String,
  },
  rolId: {
    type: Number,
  },
  data: [{
    type: Object,
    default: {
      dateInitialSesion: "2023-02-21T10:39:47-03:00",
      status: "offline",
      opcion: "0",
      dateFinalSesion: "2023-02-21T10:39:47-03:00"
    }
  }],
});
```
